---
- name: Execute Shell Scripts on java_jenkins_maven
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Pull and execute install script
      fetch:
        src: /tmp/ip-info-app/ansible/java_jenkins_maven/install.sh
        dest: /tmp/install.sh
        flat: yes
        fail_on_missing: yes
        validate_checksum: yes
      delegate_to: 10.0.1.5
      become: true
      vars:
        ansible_ssh_common_args: "-vvv -o StrictHostKeyChecking=no -i /home/ancon/.ssh/20240228.pem -l ec2-user"

    - name: Execute install script
      shell: /tmp/install.sh
      delegate_to: 10.0.1.5

    - name: Pull and execute webhook script
      fetch:
        src: /tmp/ip-info-app/ansible/java_jenkins_maven/webhook.sh
        dest: /tmp/webhook.sh
        flat: yes
        fail_on_missing: yes
        validate_checksum: yes
      delegate_to: 10.0.1.5
      become: true
      vars:
        ansible_ssh_common_args: "-vvv -o StrictHostKeyChecking=no -i /home/ancon/.ssh/20240228.pem -l ec2-user"

    - name: Execute webhook script
      shell: /tmp/webhook.sh
      delegate_to: 10.0.1.5

    - name: Pull and execute pipeline script
      fetch:
        src: /tmp/ip-info-app/ansible/java_jenkins_maven/pipeline.sh
        dest: /tmp/pipeline.sh
        flat: yes
        fail_on_missing: yes
        validate_checksum: yes
      delegate_to: 10.0.1.5
      become: true
      vars:
        ansible_ssh_common_args: "-vvv -o StrictHostKeyChecking=no -i /home/ancon/.ssh/20240228.pem -l ec2-user"

    - name: Execute pipeline script
      shell: /tmp/pipeline.sh
      delegate_to: 10.0.1.5

