- name: Transfer and execute Java and Nexus setup scripts
  hosts: nexus
  gather_facts: false
  become: true
  tasks:
    - name: Copy Java and Nexus tarballs to Nexus host
      ansible.builtin.copy:
        src: "/tmp/{{ item }}"
        dest: "/tmp/{{ item }}"
        mode: "0666"
        remote_src: true
      with_items:
        - java.tar.gz
        - nexus.tar.gz

    - name: Copy install-java-and-nexus.sh script to Nexus host
      ansible.builtin.copy:
        src: "/tmp/ip-info-app/ansible/nexus/install-java-and-nexus.sh"
        dest: "/tmp/install-java-and-nexus.sh"
        mode: "0755"
        remote_src: false

    - name: Execute install-java-and-nexus.sh script on Nexus host
      ansible.builtin.shell:
        cmd: "/bin/bash /tmp/install-java-and-nexus.sh"
      register: install_result
      ignore_errors: true

    - name: Display install-java-and-nexus.sh execution result
      debug:
        var: install_result.stdout_lines

