---
- name: Pull and execute script from Git repository
  hosts: localhost
  tasks:
    - name: Execute script.sh
      command: /bin/bash /tmp/ip-info-app/ansible/kube-argo-jump/script.sh
      become: yes
